blog/urls.py
from django.urls import path
from blog.views import create_blog_post_view, category_view, tag_view

app_name = 'blog'

urlpatterns = [
    #Post Create:
    path('create/', create_blog_post_view, name='create_blog_post_view'),

    # Kategori bazlı listeme
    path('category/<slug:category_slug>/', category_view, name='category_view'),
    
    # Etiket bazlı listeme
    path('tag/<slug:tag_slug>/', tag_view, name='tag_view'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from page.views import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Ana yapı urls'leri: 
    path('', home_view, name='home_view'),
    path('admin/', admin.site.urls),

    #User Profile
    path('user/', include('user_profile.urls', namespace='users')),

    # Blog:
    path('blog/', include('blog.urls', namespace='blog')),

    # Read:
    path('read/', include('read.urls', namespace='read')),

    # Tinymce Text Editor:
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/urls.py
from django.urls import path
from user_profile.views import (
    login_view,
    logout_view,
    register_view,
    profile_edit_view,
)

app_name = 'user_profile'

urlpatterns = [
    #Log in:
    path('login/', login_view, name='login_view'),
    # Register:
    path('register/', register_view, name='register_view'),
    #Log out:
    path('logout/', logout_view, name='logout_view'),
    #Profile Edit:
    path('profile/edit/', profile_edit_view, name='profile_edit_view'),

]

templates/core/base.html
{% load static %}
<!doctype html>
<html lang="tr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Medium Clone</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <!-- Alert Messages -->
    {% include 'core/messages.html' %}
    <!-- Alert Messages End -->
    
    <!-- Navbar -->
    {% include 'core/navbar.html' %}
    <!-- Navbar End -->

    {% block content %}
    {% endblock content %}

   

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

templates/core/base_without_navbar.html
{% load static %}
<!doctype html>
<html lang="tr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Medium Clone</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    
    <!-- Alert Messages -->
    {% include 'core/messages.html' %}
    <!-- Alert Messages End -->

    {% block content %}
    {% endblock content %}

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

templates/core/messages.html
{% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show mb-0" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    {% endif %}

templates/core/navbar.html
<!-- NAVBAR -->
<nav class="navbar navbar-expand-lg bg-warning border-bottom border-dark">
    <div class="container py-2">
        <a class="navbar-brand" href="{% url 'home_view' %}">MD Clone</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <ul class="navbar-nav ms-auto">
            <li class="nav-item">
                <a class="nav-link" href="#">Our story</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Membership</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:create_blog_post_view' %}">Write</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="{% url 'user_profile:profile_edit_view' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {{ request.user.username }}
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{{ request.user.profile.get_all_posts_url }}">My All Posts</a></li>
                    <li><a class="dropdown-item" href="#">My Favorites</a></li>
                    <li><a class="dropdown-item" href="{{ request.user.profile.get_profile_edit_url }}">Profile Edit</a></li>
                    <li><a class="dropdown-item" href="{% url 'user_profile:logout_view' %}">Log Out</a></li>
                </ul>
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user_profile:login_view' %}">Sign In</a>
            </li>
            <li class="nav-item">
                <a class="nav-link btn btn-dark text-light px-3 rounded-pill ms-1"
                    href="{% url 'user_profile:register_view' %}">Get Started</a>
            </li>


            {% endif %}
        </ul>

        <!-- <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ms-auto">
                <a class="nav-link" aria-current="page" href="#">Our story </a>
                <a class="nav-link" href="#">Membership</a>
                <a class="nav-link" href="{% url 'blog:create_blog_post_view' %}">Write</a>
                {% if request.user.is_authenticated %}
                <a class="nav-link" href="#">{{ request.user.username }}</a>
                <a class="nav-link btn btn-dark text-light px-3 rounded-pill ms-3" href="{% url 'user_profile:logout_view' %}">Log out</a>
                {% else %}
                <a class="nav-link" href="{% url 'user_profile:login_view' %}">Sign In</a>
                <a class="nav-link btn btn-dark text-light px-3 rounded-pill ms-3" href="{% url 'user_profile:register_view' %}">Get Started</a>
                {% endif %}
            </div>
        </div> -->
    </div>
</nav>
<!-- NAVBAR END -->