blog/urls.py
from django.urls import path
from blog.views import create_blog_post_view, category_view, tag_view

app_name = 'blog'

urlpatterns = [
    #Post Create:
    path('create/', create_blog_post_view, name='create_blog_post_view'),

    # Kategori bazlı listeme
    path('category/<slug:category_slug>/', category_view, name='category_view'),
    
    # Etiket bazlı listeme
    path('tag/<slug:tag_slug>/', tag_view, name='tag_view'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from page.views import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Ana yapı urls'leri: 
    path('', home_view, name='home_view'),
    path('admin/', admin.site.urls),

    #User Profile
    path('user/', include('user_profile.urls', namespace='users')),

    # Blog:
    path('blog/', include('blog.urls', namespace='blog')),

    # Read:
    path('read/', include('read.urls', namespace='read')),

    # Tinymce Text Editor:
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

read/urls.py
from django.urls import path
from .views import all_posts_view, post_detail_view

app_name = 'read'

urlpatterns = [
    # Kullanıcı yazıları
    path('<slug:user_slug>/',all_posts_view , name='all_posts_view'),
    # Post Detail
    path('<slug:user_slug>/<slug:post_slug>/',post_detail_view , name='post_detail_view'),

]

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Third Party App:
from autoslug import AutoSlugField
from tinymce.models import HTMLField


class BaseModel(models.Model):
    title = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='title', unique=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
        ordering = ('title',)


class Category(BaseModel):
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            # Buradaki adlandırma path kısmında verilen name bilgisdir.
            'blog:category_view',
            kwargs={
                "category_slug": self.slug
            }
        )


class Tag(BaseModel):

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'blog:tag_view',
            kwargs={
                "tag_slug": self.slug
            }
        )


class BlogPost(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = HTMLField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    tag = models.ManyToManyField(Tag,)
    cover_image = models.ImageField(upload_to='post')
    view_count = models.PositiveBigIntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-created_at',)

    def get_absolute_url(self):
        return reverse(
            'read:post_detail_view',
            kwargs={
                "user_slug": self.user.profile.slug,
                "post_slug": self.slug
            }
        )

read/models.py
from django.db import models

# Create your models here.

read/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import BlogPost, Tag
from user_profile.models import Profile

def all_posts_view(request, user_slug):
    profile = get_object_or_404(Profile, slug=user_slug)
    posts = BlogPost.objects.filter(is_active=True, user=profile.user)
    context = dict(
        posts = posts,
        profile = profile,
    )
    return render(request, 'read/all_posts.html', context)

def post_detail_view(request, user_slug, post_slug):
    post = get_object_or_404(BlogPost, slug=post_slug, is_active=True)
    post.view_count +=1
    post.save()
    context = dict(
        post=post,
    )
    return render(request, 'read/post_detail.html', context)

read/templates/read/all_posts.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-8 offset-sm-2 mt-5">

            {% if category %}
            <h2>K: {{ category.title|upper }}</h2>
            {% elif tag %}
            <h2>T: {{ tag.title|upper }}</h2>
            {% elif profile %}
            <h2>My All Posts: {{ profile.user }}</h2>
            {% endif %}

        </div>
        <div class="col-sm-8 offset-sm-2 mt-5">
            {% if category %}
                {% with posts=category.blogpost_set.all %}
                    {% for post in posts %}
                        {% include 'blog/components/post.html' %}
                    {% endfor %}
                {% endwith %}
            {% elif profile %}
                {% with posts=profile.user.blogpost_set.all %}
                    {% for post in posts %}
                        {% include 'blog/components/post.html' %}
                    {% endfor %}
                {% endwith %}
            {% else %}
                {% with posts=tag.blogpost_set.all %}
                    {% for post in posts %}
                        {% include 'blog/components/post.html' %}
                    {% endfor %}
                {% endwith %}
            {% endif %}

        </div>
    </div>
</div>
{% endblock content %}

read/templates/read/post_detail.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container mt-2">
            {% include 'read/components/post.html' %}
    </div>
</div>
{% endblock content %}